### ISSUE TITLE
Not working, what to try?

### ISSUE THREAD

**Issue by antoniomo** [jwilm/i3-vim-focus#1]
Hi!

Unfortunately it doesn't seem to work on my configuration.

I made sure to have the vim bindings configured (`gw+direction) as well as setting the window name to VIM (set titlestring=VIM). I also have the bindings on i3 config, and my vim is compiled with python support.

Anything else I could check/try?

Thanks!
Antonio

**Comment by XyloVech** [comment]
In your .i3/config file add:

`bindsym --release $mod+Left exec "i3-vim-focus left"`
`bindsym --release $mod+Down exec "i3-vim-focus down"`
`bindsym --release $mod+Up exec "i3-vim-focus up"`
`bindsym --release $mod+Right exec "i3-vim-focus right"`


instead of the recommended bindings from the project's readme.
The `--release` does the trick by triggering the binding upon key release.

**Comment by antoniomo** [comment]
Awesome! Thanks!
